name: Deploy to AWS

on:
  workflow_dispatch:
  push:
#    branches-ignore: # Disable
#      - '**'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Reload server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: bash -c -l "~/www/onten2023/start.sh"
